# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (four digits)'
        required: true
        default: 'X.X.X.X'
      description:
        description: 'Description for the release (optional)'
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - run: npm ci
      #- run: npm run test
      - run: npm run useChrome
      - run: npm run build
      - run: cd build && zip -r ../TUfast_TUD_chrome.zip *

      - run: npm run useFF
      - run: npm run build
      - run: cd build && zip -r ../TUfast_TUD_firefox.zip *

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "TUfast_TUD_chrome.zip,TUfast_TUD_firefox.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}

